global:
  tlsSecret: one37id-tls-dev

# Overide values for the keycloak subchart
keycloak:
  nameOverride: one37id-keycloak
  fullnameOverride: one37id-keycloak
  global:
    storageClass: "ibmc-vpc-block-general-purpose"
  image:
    pullpolicy: "Always"
  auth:
    adminPassword: "one37id"
    adminUser: "admin"
  containerPorts:
    http: 8080
    https: 8443
  service:
    type: ClusterIP
    port: 8080
  ingress:
    enabled: true
    className: "public-iks-k8s-nginx"
    hosts:
      - paths:
          - path: /
            pathType: Prefix
            port: 8080
    tls:
      - secretName: tlsSecret
        hosts:
          - ibm-agentjs.dev-one37.id

  postgresql:
    enabled: true
    auth:
      postgresPassword: ""
      username: bn_keycloak
      password: ""
      database: bitnami_keycloak
      existingSecret: ""
      secretKeys:
        userPasswordKey: password
    architecture: standalone

  # master:
  #   persistence:
  #     size: 10Gi
  #     persistentVolumeClaimRetentionPolicy:
  #       enabled: true
  #       whenScaled: Retain
  #       whenDeleted: Delete
  # replica:
  #   replicaCount: 1
  #   persistence:
  #     size: 10Gi