global:
  tlsSecret: one37id-tls-dev

# Overide values for the keycloak subchart
keycloak:
  nameOverride: one37id-keycloak
  fullnameOverride: one37id-keycloak
  global:
    storageClass: ibmc-vpc-block-general-purpose
  image:
    pullpolicy: Always
  auth:
    adminPassword: one37id
    adminUser: admin
  containerPorts:
    http: 8080
    https: 8443
  service:
    type: ClusterIP
    http:
      enabled: true
    ports:
      http: 80
      https: 443
  proxy: edge
  tls:
    enabled: false
    existingSecret: one37id-tls-dev
  ingress:
    enabled: true
    ingressClassName: public-iks-k8s-nginx
    hostname: keycloak.dev-one37.id
    tls: false
    extraTls:
    - hosts:
        - keycloak.dev-one37.id
      secretName: one37id-tls-dev

  logging:
    output: default
    level: DEBUG

  postgresql:
    enabled: true
    auth:
      postgresPassword: "postgres"
      username: bn_keycloak
      password: "keycloak"
      database: bitnami_keycloak
    architecture: standalone
