apiVersion: v2
name: one37id-ibm-agentjs
type: application
description: A Helm chart to deploy the One37 Business Connector Agent JS
home: https://one37id.com
icon: https://www.one37id.com/images/connector.svg
annotations:
  category: Infrastructure
  licenses: Apache-2.0
dependencies:
  - name: one37id-ibm-agent
    repository: file://../one37id-ibm-agent
    tags:
    - one37id-ibm-agent
    version: 1.2408.21-1
keywords:
  - businessconnector
  - ssi
  - oid4vc
  - agent
  - one37id
  - one37
  - one37id.com
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.2408.21-1"
version: 1.2408.21-1
