{{- if .Values.volume.enabled }}
{{- $fullName := include "one37id-bc-ctrl.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName}}-{{ .Values.volume.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.volume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
{{- end }}
