{{- $fullName := include "one37id-ibm-agent.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}