# Overide values for the redis subchart
redis:
  nameOverride: "one37id-redis"
  fullnameOverride: "one37id-redis"
  global:
    storageClass: "ibmc-vpc-block-general-purpose"
  master:
    persistence:
      size: 10Gi
      persistentVolumeClaimRetentionPolicy:
        enabled: true
        whenScaled: Retain
        whenDeleted: Delete
  replica:
    replicaCount: 1
    persistence:
      size: 10Gi

