apiVersion: v1
kind: Service
metadata:
  name: {{include "one37id-workflow.fullname" .}}
  labels: {{- include "one37id-workflow.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: http
  selector: {{- include "one37id-workflow.selectorLabels" . | nindent 4}}
