apiVersion: v2
name: one37id-bc
type: application
description: A Helm chart to deploy the One37 Business Connector
home: https://one37id.com
icon: https://www.one37id.com/images/connector.svg
annotations:
  category: Infrastructure
  licenses: Apache-2.0
dependencies:
  - name: one37id-bc-ctrl
    repository: file://../one37id-bc-ctrl
    tags:
    - one37id-bc-ctrl
    version: 2.2408.22-1
keywords:
  - businessconnector
  - ssi
  - oid4vc
  - agent
  - one37id
  - one37
  - one37id.com
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "2.2408.22-1"
version: 2.2408.22-1
