{{- $fullName := include "one37id-ibm-studio.fullname" . -}}
{{- $justName := include "one37id-ibm-studio.name" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcRoot := printf "%s:%v" "http://0.0.0.0" .Values.service.port -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
data:
  STUDIO_PG_DBNAME: {{ $justName }}-db
  SERVICE_ROOT: {{ $svcRoot | quote }}
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}