# Overide values for the postgres subchart
postgresql:
  nameOverride: "one37id-pgsql"
  fullnameOverride: "one37id-pgsql"
  global:
    storageClass: "ibmc-vpc-block-general-purpose"
  image:
    pullPolicy: Always
  primary:
    persistence:
      size: 20Gi
  backup:
    enabled: true
    persistence:
      size: 20Gi
